---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mosquitto-passwd
  namespace: mqtt
spec:
  encryptedData:
    passwd: AgBCqgHrjlkcLLr52gTWRLYrIX0XvXkJmPszT6sDGRpGrTtbr1SD/iKfEJVKPThfrZknu9UygrodsbL3odwwTfiNir7a8uYPYx8Y2NETHVBC21OMnNsf64GaEpNbazk5s5nWIcFI36DXcoPoIMJ+bTniEBREpCRZVbUywGGnE9DBnRT+Zvrr/aNuW0V7QVuOetCYLsrdTx9WQwDi6wX2/WsH6bKfdT9k99SJYstD+sKHY2y9fzxH1pyUg3mcBMAisoiIKkdgs31W9tYzLaDQyvb/aLJJtJqMvI22o+NzCpGDuGiZyXuUJVD8/P7ZYQYLOfouMZkEFA+X6gb0HpTjA7eDk+M+5GPiOHBWsubZynFr85UUuohcvgNE6vzdOSR71B+psiBFTVahcy2BE8t5pcmhCRkf5sCToEgM4LoavG+uJUMHzgpgR1I6ewkSjjKaMqDnp18u2UEjmhWYP2qQ5QypGLqhb6CqPCpofyytZhsvBVNgWwvnbYPhr/AWpb+M+O9FdxT6gtOexVnbLs/0+Ks8/OLqkekZktCcV0bVcUlEvCE6MLhxS96Ec/FsDiPkW3lJ04NiGYmtbFIU3D4YmVjLrcJzo7xhJysaNQUK33/V6eafKWPlJXmO0xToJwgDdM179JfjpXRw/XdUehupj6kta+DZ4RFFF3lb0eO5I46YrgPeC0qOwLmAq8kDxdwg0zSGhABUNS3CxJG+YswjojZynu+gAcLU1nK7I1pzfQtTG8io6uPYr4su7INI2nydcFvQSAxXAu8Vzocv/epULEs22SMjxV/hSMvC8h0BcUfzT6xuqSh54M6a/2ETFhEEySTlcowjQA1CfRJZHANIp/dZF5Ob3HoeZqaeaHMAMA==
  template:
    metadata:
      creationTimestamp: null
      name: mosquitto-passwd
      namespace: mqtt
