apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: planka

labels:
- pairs:
    environment: homelab
- includeSelectors: true
  pairs:
    app: planka

resources:
- database.yaml
- pvcs.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- sealed-secrets/planka-planka-authentik-oidc-credentials-sealed.yaml
- sealed-secrets/planka-planka-database-secret-sealed.yaml
- sealed-secrets/planka-planka-secret-sealed.yaml
- sealed-secrets/planka-planka-smtp-sealed.yaml

images:
- name: planka
  newName: ghcr.io/plankanban/planka
  newTag: 2.0.0-rc.4
