apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie

labels:
- pairs:
    environment: homelab
- includeSelectors: true
  pairs:
    app: mealie

resources:
- namespace.yaml
- database.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- sealed-secrets/mealie-mealie-authentik-oidc-credentials-sealed.yaml
- sealed-secrets/mealie-mealie-database-secret-sealed.yaml
- sealed-secrets/mealie-mealie-smtp-sealed.yaml

images:
- name: mealie
  newName: ghcr.io/mealie-recipes/mealie
  newTag: v3.10.2
