---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    release_namespace: kube-system
    repo: https://bitnami-labs.github.io/sealed-secrets
    valuesInline:
      fullnameOverride: "sealed-secrets-controller"
    includeCRDs: true
    version: 0.29.0
