---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    valuesInline:
      fullnameOverride: "sealed-secrets-controller"
    includeCRDs: true
    version: 2.18.1
