---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-data-iscsi
spec:
  storageClassName: ""
  volumeName: immich-library-data-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-data-iscsi
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.2.169:3260
    iqn: iqn.2013-03.com.wdc:secretmemestash:immich-library-data
    lun: 0
    fsType: ext4
